improve code to detect changes

diff --git a/git-wip b/git-wip
--- a/git-wip
+++ b/git-wip
@@ -23,9 +23,9 @@ Commands:
         git wip delete [<branch>] - delete a WIP branch
 
 Options for save:
-        --editor                  - be less verbose, assume called from an editor
-        --untracked               - capture also untracked files
-        --ignored                 - capture also ignored files
+        -e --editor               - be less verbose, assume called from an editor
+        -u --untracked            - capture also untracked files
+        -i --ignored              - capture also ignored files
 
 Options for log:
         -p --pretty               - show a pretty graph
@@ -74,10 +74,6 @@ get_wip_branch () {
         return 0
 }
 
-find_changes () {
-        git ls-files --exclude-standard --cached -m $@
-}
-
 check_files () {
         local files=$@
 
@@ -96,26 +92,52 @@ report_no_changes () {
         die "no changes"
 }
 
+build_new_tree () {
+        local untracked=$1 ; shift
+        local ignored=$1 ; shift
+        local files=$@
+
+        (
+        set -e
+        rm -f $WIP_INDEX
+        cp -p $GIT_DIR/index $WIP_INDEX
+        export GIT_INDEX_FILE=$WIP_INDEX
+        git read-tree $wip_parent
+        if [ -n "$files" ]
+        then
+                git add $files
+        else
+                git add -u
+        fi
+        [ -n "$untracked" ] && git add .
+        [ -n "$ignored" ] && git add -f -A .
+        git write-tree
+        rm -f "$WIP_INDEX"
+        )
+}
+
 do_save () {
         local msg=$1 ; shift
-        local ls_files_extra=
+        local add_untracked=
+        local add_ignored=
 
         while test $# != 0
         do
                 case "$1" in
-                        --editor)
+                -e|--editor)
                         EDITOR_MODE=true
                         ;;
-
-                        --untracked|--ignored)
-                        ls_files_extra="$LS_FILES_EXTRA $1"
+                -u|--untracked)
+                        add_untracked=t
                         ;;
-
-                        --)
+                -i|--ignored)
+                        add_ignored=t
+                        ;;
+                --)
                         shift
                         break
                         ;;
-                        *)
+                *)
                         [ -f "$1" ] && break
                         die "Unknown option '$1'."
                         ;;
@@ -123,12 +145,11 @@ do_save () {
                 shift
         done
         local files=$@
+        local "add_untracked=$add_untracked"
+        local "add_ignored=$add_ignored"
 
-        if test ${#files} -eq 0
+        if test ${#files} -gt 0
         then
-                files=$(find_changes ls_files_extra)
-                [ ${#files} -eq 0 ] && report_no_changes
-        else
                 check_files $files
         fi
 
@@ -168,14 +189,8 @@ do_save () {
 
         dbg "wip_parent=$wip_parent"
 
-        new_tree=$( ( rm -f $WIP_INDEX \
-                  && cp -p $GIT_DIR/index $WIP_INDEX \
-                  && export GIT_INDEX_FILE=$WIP_INDEX \
-                  && git read-tree $wip_parent \
-                  && git add $files \
-                  && git write-tree \
-                  && rm -f "$WIP_INDEX" ) 
-        ) || die "Cannot save the current worktree state."
+        new_tree=$( build_new_tree "$add_untracked" "$add_ignored" $files ) \
+        || die "Cannot save the current worktree state."
 
         dbg "new_tree=$new_tree"
 
@@ -307,3 +322,5 @@ delete)
         exit 1
         ;;
 esac
+
+# vim: set noet sw=8
